name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup update

      - name: Check formatting
        run: cargo fmt --check

      - name: Run tests
        run: cargo test --all
